/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Cultivar } from "./Cultivar";
import { CultivarCountArgs } from "./CultivarCountArgs";
import { CultivarFindManyArgs } from "./CultivarFindManyArgs";
import { CultivarFindUniqueArgs } from "./CultivarFindUniqueArgs";
import { DeleteCultivarArgs } from "./DeleteCultivarArgs";
import { CultivarService } from "../cultivar.service";
@graphql.Resolver(() => Cultivar)
export class CultivarResolverBase {
  constructor(protected readonly service: CultivarService) {}

  async _cultivarsMeta(
    @graphql.Args() args: CultivarCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Cultivar])
  async cultivars(
    @graphql.Args() args: CultivarFindManyArgs
  ): Promise<Cultivar[]> {
    return this.service.cultivars(args);
  }

  @graphql.Query(() => Cultivar, { nullable: true })
  async cultivar(
    @graphql.Args() args: CultivarFindUniqueArgs
  ): Promise<Cultivar | null> {
    const result = await this.service.cultivar(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Cultivar)
  async deleteCultivar(
    @graphql.Args() args: DeleteCultivarArgs
  ): Promise<Cultivar | null> {
    try {
      return await this.service.deleteCultivar(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
