/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Commodity } from "./Commodity";
import { CommodityCountArgs } from "./CommodityCountArgs";
import { CommodityFindManyArgs } from "./CommodityFindManyArgs";
import { CommodityFindUniqueArgs } from "./CommodityFindUniqueArgs";
import { DeleteCommodityArgs } from "./DeleteCommodityArgs";
import { CommodityService } from "../commodity.service";
@graphql.Resolver(() => Commodity)
export class CommodityResolverBase {
  constructor(protected readonly service: CommodityService) {}

  async _commoditiesMeta(
    @graphql.Args() args: CommodityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Commodity])
  async commodities(
    @graphql.Args() args: CommodityFindManyArgs
  ): Promise<Commodity[]> {
    return this.service.commodities(args);
  }

  @graphql.Query(() => Commodity, { nullable: true })
  async commodity(
    @graphql.Args() args: CommodityFindUniqueArgs
  ): Promise<Commodity | null> {
    const result = await this.service.commodity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Commodity)
  async deleteCommodity(
    @graphql.Args() args: DeleteCommodityArgs
  ): Promise<Commodity | null> {
    try {
      return await this.service.deleteCommodity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
