/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeliveryRun } from "./DeliveryRun";
import { DeliveryRunCountArgs } from "./DeliveryRunCountArgs";
import { DeliveryRunFindManyArgs } from "./DeliveryRunFindManyArgs";
import { DeliveryRunFindUniqueArgs } from "./DeliveryRunFindUniqueArgs";
import { DeleteDeliveryRunArgs } from "./DeleteDeliveryRunArgs";
import { DeliveryRunService } from "../deliveryRun.service";
@graphql.Resolver(() => DeliveryRun)
export class DeliveryRunResolverBase {
  constructor(protected readonly service: DeliveryRunService) {}

  async _deliveryRunsMeta(
    @graphql.Args() args: DeliveryRunCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DeliveryRun])
  async deliveryRuns(
    @graphql.Args() args: DeliveryRunFindManyArgs
  ): Promise<DeliveryRun[]> {
    return this.service.deliveryRuns(args);
  }

  @graphql.Query(() => DeliveryRun, { nullable: true })
  async deliveryRun(
    @graphql.Args() args: DeliveryRunFindUniqueArgs
  ): Promise<DeliveryRun | null> {
    const result = await this.service.deliveryRun(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeliveryRun)
  async deleteDeliveryRun(
    @graphql.Args() args: DeleteDeliveryRunArgs
  ): Promise<DeliveryRun | null> {
    try {
      return await this.service.deleteDeliveryRun(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
